# Generated by Django 2.2.16 on 2022-09-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='users',
        ),
    ]
