# Generated by Django 2.2.16 on 2022-09-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220908_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='users',
            new_name='user',
        ),
    ]
